# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/geospatial',
                'doc_host': 'https://JuanDiaz12000.github.io',
                'git_url': 'https://github.com/JuanDiaz12000/geospatial',
                'lib_path': 'geospatial'},
  'syms': {'geospatial.core': {'geospatial.core.foo': ('core.html#foo', 'geospatial/core.py')}}}
